### ISSUE TITLE
Microsoft Edge Javascript Issue

### ISSUE THREAD

**Issue by unkleho** [slnsw/dxlab-fellowship-2019#43]
Hi Mauricio, 

Hope you are well, very excited to have a launch date for your project!

Unfortunately we have run into an issue with Microsoft Edge:
![image](https://user-images.githubusercontent.com/1124027/85644414-35cd6380-b6da-11ea-9a60-eb7b1ce4f839.png)
![image](https://user-images.githubusercontent.com/1124027/85644411-349c3680-b6da-11ea-8c2c-c22da0561e4b.png)

I think it is because of some ES6 syntax that Edge can't handle. Is it possible to try and update the `tsconfig.json` target from `es6` to `es5` and recompile? I've done this for other projects and it helps with Edge.

If it doesn't work, we may need to have some fallback text to suggest other browsers to use.

Thanks
Kaho

**Comment by mgiraldo** [comment]
oh boy i just saw this... yeah it seems like an additional transpile needs to be done or remove ES6-specific syntax... will look into it

**Comment by mgiraldo** [comment]
what version of Edge is this?

**Comment by unkleho** [comment]
Edge 44.17763.831.0
From 2018
So not latest version, but a lot of people will still have this. 
Hopefully changing the setting to es5 and transpiling again will work. Thanks!

**Comment by mgiraldo** [comment]
I have confirmed that Aereo works with the latest version of Edge. how critical is it to support version 44?

**Comment by mgiraldo** [comment]
i tried multiple additional export settings and none solved the issue with Edge 18 (which is the engine for Edge 44). whoever is running Edge 18 can upgrade to the latest or use Firefox, Opera, or Chrome which work fine.
